### ISSUE TITLE
CKNotification cast to CKQueryNotification

### ISSUE THREAD

**Issue by yoonack** [evermeer/EVCloudKitDao#9] opened 2015-06-01 03:51 UTC
I just found an error occurred during startup, "Could not cast value of type 'CKNotification' (0x35cde2ac) to 'CKQueryNotification' (0x35cde2d4)." in the line : var queryNotification: CKQueryNotification = cloudNotification as! CKQueryNotification. This is inside the function didReceiveRemoteNotification() in the EVCloudKitDao.swift. I think its the downcast problem.

**Comment by evermeer** [comment] 2015-06-01 06:09
That's strange, As you can see in the line above, I'm checking if the notificationtypg is query. I will change that assignment in an 'if var = .. as? ..' construction. That should at least fix the crash.

I'm puzzled in what case you could get a notification of type query that is not a CKQueryNotification...

**Comment by yoonack** [comment] 2015-06-01 06:19
i have no idea what type of notifcation i am getting, it says push received. Then, the crash happens. However, I haven't changed anything to initiate the notification

**Comment by evermeer** [comment] 2015-06-01 06:28
I just pushed version 2.1.1 to GitHub where the cast will be conditional with an 'if var' construction. You should not get a crash anymore. Could you try that version? In your case instead of a crash you should see 3 lines in the output log that start with '===>' If you do see those lines, could you put them in this issue? Thanks.

**Comment by yoonack** [comment] 2015-06-01 06:35
Should not happen, please put this and the 2 lines below in a github issue.
==>notificationType is Query but the notification is not a CKQueryNotification.
===>notification = <CKNotification: 0x15efa0c0; notificationType=0, notificationID=<CKNotificationID: 0x15ef0d40;

This is what I get from the message

**Comment by evermeer** [comment] 2015-06-01 07:16
The code that I use is similar to: 
https://developer.apple.com/library/mac/documentation/DataManagement/Conceptual/CloudKitQuickStart/SubscribingtoRecordChanges/SubscribingtoRecordChanges.html 
Section: Handle Push Notifications in Code

But in swift the cast to CKQueryNotification fails where it works in Objective C. The only thing I can think of is to recreate the CKQueryNotification object. I just committed that to GitHub as release 2.1.2

I'm sorry for making you the tester for this, but could you please try this latest version?

**Comment by yoonack** [comment] 2015-06-01 07:49
I just updated to the new version, however, I am not able to see the result since the server is not sending me this weird pushed received. I will see if the problem still exits and let you know in the future. Thanks for the great library!

**Comment by evermeer** [comment] 2015-06-01 09:10
Great to hear that it's used actively. I'm using it in my own project and every bug found will also benefit my project. I will leave this issue open for now until there is confirmation that it has been solved.

**Comment by evermeer** [comment] 2015-06-02 18:19
I was able to reproduce this issue. I do believe it's a CloudKit bug and created an Apple bug report for it (rdar://21204702) The notification will be ignored. I can't do anything else with it because it does not contain any information other than it's ID.

**Closed** 2015-06-04 08:37 UTC
